### ISSUE TITLE
Naked domain not working.

### ISSUE THREAD

**Issue by mykewould** [cknadler/gitfeats.com#16]
gitfeats.com does not work and is linked in various places including the git-feats gem README

This is a common problem with heroku.

https://devcenter.heroku.com/articles/avoiding-naked-domains-dns-arecords

**Comment by cknadler** [comment]
Nice catch. Will try to get this fixed today.

Sent from my iPhone

On Dec 17, 2012, at 3:16 PM, Michael Wood notifications@github.com wrote:

gitfeats.com does not work and is linked in various places including the
git-feats gem README

This is a common problem with heroku.

https://devcenter.heroku.com/articles/avoiding-naked-domains-dns-arecords

—
Reply to this email directly or view it on
GitHubhttps://github.com/cknadler/gitfeats.com/issues/16.

**Comment by cknadler** [comment]
Fixed. If my latency with issues is high this week, blame finals. Back on track full steam next week.
