### ISSUE TITLE
Problem with Api key when user has "-" in github username

### ISSUE THREAD

**Issue by dasmoose** [cknadler/gitfeats.com#5]
Was trying to do some testing and created a guthub account named "dasmoose-test"

git config --global feats.key "dasmoose-test-96099b933102b00a62c65c11b77967c7c71f842d"

The website is trying to find a user with the nickname "dasmoose" and the key of "test"

Not sure how you guys want to handle this.....

**Comment by cknadler** [comment]
We will probably have to have two separate fields in the config file:

```
username: dasmoose-test
key: 96099b933102b00a62c65c11b77967c7c71f842d
```

**Comment by cknadler** [comment]
Or we can leverage the fact that the user is definitely using github and likely has their username already present in the config file.

So it would look like this:

```
[github]
  user = cknadler

[feats]
  key = e2142bed7680c9469ee32463f5acfc3f71aa4389
```
