### ISSUE TITLE
Error rendering public_pages#stats

### ISSUE THREAD

**Issue by cknadler** [cknadler/gitfeats.com#6]
I have a feeling it's just something I'm forgetting but I've been staring at it for a while now with no luck.

`app/views/public_pages/stats.html.erb, line 40`

```
var num_commands = <%= raw @top_commands.count.to_json %>;
```

Blowing up there for me with the database empty (no user data, still seeded) and when it has my single user's data.

**Comment by ieckert** [comment]
Could check that @top_commands is getting populated. maybe a nil object error? I am free at 2, so we could look at it then?

**Comment by cknadler** [comment]
Nil. Yeah 2 works.

Sent from my iPhone

On Dec 10, 2012, at 9:24 AM, Ian Eckert notifications@github.com wrote:

Could check that @top_commands is getting populated. maybe a nil object
error? I am free at 2, so we could look at it then?

—
Reply to this email directly or view it on
GitHubhttps://github.com/cknadler/gitfeats.com/issues/6#issuecomment-11207654.

**Comment by ieckert** [comment]
sorry for the trouble man. I didn't check it without data last night, so most likely that is the problem. Either that, or my changes to how @top_commands gets populated didn't get pushed up or something.

**Comment by cknadler** [comment]
This is actually still breaking.

`app/views/public_pages/stats.html.erb, line 6`

``` ruby
<% @top_users.each do |top_user| %>
```

**Comment by cknadler** [comment]
When testing, try to hit the root_path, not though the web interface. That is where this is breaking, a simple `localhost:3000`.
